server:
  port: 8084
spring:
  application:
    name: hystrix-user-service
  cloud:
    nacos:
      discovery:
        group: HYSTRIX-SERVICE-GROUP
        server-addr: 192.168.66.9:8848
        namespace: 9739d612-297a-4a7c-b098-6090edf88dea