server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
spring:
  application:
    name: hystrix-consumer-demo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.9:8848
        namespace: 9739d612-297a-4a7c-b098-6090edf88dea
        group: HYSTRIX-SERVICE-GROUP
        fail-fast: true