server:
  port: 8080
  undertow:
    threads:
      #懒加载方式，请求进来进行创建线程
      #官方认为CPU*10是一个很高的数值,源码建议:工作线程=非阻塞线程*8（阻塞系数）
      #IO阻塞线程，请求进来时创建，当达到工作线程数时一直保持活跃至程序停止
      worker: 256
      #I/O线程数=CPU*2  初始化非阻塞线程,一直保持活跃
      io: 32
    #开辟直接内存
    direct-buffers: true
    #16*1024-20=16364 见源码详解
    #写入buffer中的最大值
    buffer-size: 16364