server:
  port: 8090
spring:
  application:
    name: openfegin-httpclient-demo
  cloud:
    nacos:
      discovery:
        namespace: 9739d612-297a-4a7c-b098-6090edf88dea
        server-addr: 192.168.66.9:8848
        fail-fast: true
        register-enabled: false
        group: ALI-TEST-SERVICE-GROUP
  main:
    allow-bean-definition-overriding: true
feign:
  okhttp:
    enabled: true
    connectTimeout: 20000
    readTimeout: 20000
    writeTimeout: 20000
    retryOnConnectionFailure: true
    maxIdleConnections: 10
    keepAliveDuration: 30000
  #不配置会拿RibbonClientConfiguration。ribbonClientConfig()默认值
  #不配置feign默认配置会进行重试，但是具体走哪一个重试机制未知(待验证)
  client:
    config:
      default:
        read-timeout: 60000 #请求的读取超时时长，单位：毫秒。默认为 60 * 1000 毫秒
        connect-timeout: 5000 #请求的连接超时时长，单位：毫秒。默认为 10 * 1000 毫秒
        logger-level: BASIC
logging:
  level:
    com.springcloud.alibaba.demo.openfegin.service: DEBUG
