server:
  port: 8081
  tomcat:
    #最大连接数
    max-connections: 8192
    #连接请求队列最大数
    #提高吞吐量参数
    accept-count: 1000
    #连接请求超时
    connection-timeout: 60000
    threads:
      #工作队列最大数
      #提高吞吐量参数(最大活躍綫程數,活躍時間60s,超過60s綫程退出)
      max: 256
      #工作队列最小数(最少活躍綫程數)  与服务系统CPU数量有关 可以初始化为CPU数量或者CPU数量*2
      min-spare: 32
    #将保留在缓存中并与后续请求一起重用的空闲处理器的最大数量。当设置为-1时，缓存将不受限制，其理论最大大小等于最大连接数。
    #提高吞吐量参数
    processor-cache: 1000