server:
  port: 8090
spring:
  application:
    name: ribbon-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.9:8848
        fail-fast: true
        register-enabled: false
        group: ALI-TEST-SERVICE-GROUP
        namespace: 9739d612-297a-4a7c-b098-6090edf88dea
#客户端级别的自定义配置
nacos-provider:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则全类名
    NFLoadBalancerRuleClassName: com.springcloud.alibaba.demo.loadbalance.VersionRoundRobbinRule
    Version: 1.0.0
ribbon:
  eager-load:
    enabled: true #是否开启饥饿加载。默认为 false 不开启
    clients: nacos-provider # 开启饥饿加载的 Ribbon 客户端名字。如果有多个，使用 , 逗号分隔。