server:
  port: 8090
spring:
  application:
    name: ribbon-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.9:8848
        fail-fast: true
        register-enabled: false
        group: ALI-TEST-SERVICE-GROUP
        namespace: 9739d612-297a-4a7c-b098-6090edf88dea
#客户端级别的自定义配置
nacos-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则全类名